AWSTemplateFormatVersion: 2010-09-09
Description: MyMeta Market Store
Parameters:
  DomainName:
    Type: String
    Default: playmymeta.app
  EnvironmentName:
    Type: String
    AllowedValues:
      - development
      - staging
      - production
    Default: development
  ShortStackName:
    Type: String
    Default: store
  HostedZoneId:
    Type: String
    Default: Z0656490M8JKWQ93YJX2

Mappings:
  MetaStoreBucketNames:
    development:
      Name: "store.dev.playmymeta.app"
    staging:
      Name: "store.staging.playmymeta.app"
    production:
      Name: "store.playmymeta.app"
  MetaStoreDomainNames:
    development:
      Name: store.dev.playmymeta.app
    production:
      Name: store.playmymeta.app

Resources:
  MetaStoreBucketAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join
          - "-"
          - - mymeta
            - "access-identity-bucket"
            - !Ref ShortStackName
            - !Ref EnvironmentName
  MetaStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOriginalCopiesRule
            Prefix: original
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: !Join
        - "-"
        - - mymeta
          - !Ref ShortStackName
          - bucket
          - !Ref EnvironmentName
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Application Name
          Value: mymeta-store
  MetaStoreBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MetaStoreBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${MetaStoreBucketAccessIdentity}
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${MetaStoreBucket}/*"
  MetaStoreDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_All
        Aliases:
          - !FindInMap ["MetaStoreBucketNames", !Ref EnvironmentName, "Name"]
        Origins:
          - DomainName: !GetAtt MetaStoreBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${MetaStoreBucketAccessIdentity}
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:894223418767:certificate/7009bce0-3d2c-4e4e-a117-f911500521ed
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 3600
          MaxTTL: 86400
          MinTTL: 60
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
  MetaStoreDNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z0656490M8JKWQ93YJX2
      RecordSets:
        - Name: !FindInMap ["MetaStoreDomainNames", !Ref EnvironmentName, "Name"]
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt MetaStoreDistribution.DomainName
          SetIdentifier: !GetAtt MetaStoreDistribution.DomainName
          Weight: 1
        - Name: !FindInMap ["MetaStoreDomainNames", !Ref EnvironmentName, "Name"]
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt MetaStoreDistribution.DomainName
          SetIdentifier: !GetAtt MetaStoreDistribution.DomainName
          Weight: 1